Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.network "forwarded_port", guest: 80, host: 8090 # localhosst
  config.vm.network "public_network", ip: "192.168.1.55" # rede publica
  config.vm.provision "shell",
    #inline: "apt update && apt -y install nginx && service nginx start" #comando para atualizar, instala o nginx na vm e starta o nginx - inline
    path: "script.sh" # caminho do arquivo onde está o script para instalação do nginx
  config.vm.synced_folder "site/", "/var/www/html" # pega oque está na pasta site e joga na html, sincronizando

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
  
end


# vagrant suspend , salva o estado
# vagrant resume, reestarta