Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.network "forwarded_port", guest: 80, host: 8090 # localhosst
  # config.vm.network "public_network" # rede publica
  config.vm.provision "shell",
    inline: "apt update && apt -y install nginx && service nginx start" #comando para atualizar, instala o nginx na vm e starta o nginx
end


# vagrant suspend , salva o estado
# vagrant resume, reestarta